version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/projects/src/harmony
hooks:
  BeforeInstall:
    - location: aws-scripts/say_hello.sh
      timeout: 10
      runas: root
  AfterInstall:
    - location: aws-scripts/setup.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: aws-scripts/run_instance.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: aws-scripts/say_bye.sh
      timeout: 10
      runas: root
