// Code generated by protoc-gen-go. DO NOT EDIT.
// source: downloader.proto

package downloader

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DownloaderRequest_RequestType int32

const (
	DownloaderRequest_HEADER   DownloaderRequest_RequestType = 0
	DownloaderRequest_BLOCK    DownloaderRequest_RequestType = 1
	DownloaderRequest_NEWBLOCK DownloaderRequest_RequestType = 2
	DownloaderRequest_REGISTER DownloaderRequest_RequestType = 3
	DownloaderRequest_UNKOWN   DownloaderRequest_RequestType = 4
)

var DownloaderRequest_RequestType_name = map[int32]string{
	0: "HEADER",
	1: "BLOCK",
	2: "NEWBLOCK",
	3: "REGISTER",
	4: "UNKOWN",
}

var DownloaderRequest_RequestType_value = map[string]int32{
	"HEADER":   0,
	"BLOCK":    1,
	"NEWBLOCK": 2,
	"REGISTER": 3,
	"UNKOWN":   4,
}

func (x DownloaderRequest_RequestType) String() string {
	return proto.EnumName(DownloaderRequest_RequestType_name, int32(x))
}

func (DownloaderRequest_RequestType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_6a99ec95c7ab1ff1, []int{0, 0}
}

type DownloaderResponse_RegisterResponseType int32

const (
	DownloaderResponse_SUCCESS DownloaderResponse_RegisterResponseType = 0
	DownloaderResponse_FAIL    DownloaderResponse_RegisterResponseType = 1
	DownloaderResponse_INSYNC  DownloaderResponse_RegisterResponseType = 2
)

var DownloaderResponse_RegisterResponseType_name = map[int32]string{
	0: "SUCCESS",
	1: "FAIL",
	2: "INSYNC",
}

var DownloaderResponse_RegisterResponseType_value = map[string]int32{
	"SUCCESS": 0,
	"FAIL":    1,
	"INSYNC":  2,
}

func (x DownloaderResponse_RegisterResponseType) String() string {
	return proto.EnumName(DownloaderResponse_RegisterResponseType_name, int32(x))
}

func (DownloaderResponse_RegisterResponseType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_6a99ec95c7ab1ff1, []int{1, 0}
}

// DownloaderRequest is the generic download request.
type DownloaderRequest struct {
	// Request type.
	Type DownloaderRequest_RequestType `protobuf:"varint,1,opt,name=type,proto3,enum=downloader.DownloaderRequest_RequestType" json:"type,omitempty"`
	// The hashes of the blocks we want to download.
	Hashes               [][]byte `protobuf:"bytes,2,rep,name=hashes,proto3" json:"hashes,omitempty"`
	PeerHash             []byte   `protobuf:"bytes,3,opt,name=peerHash,proto3" json:"peerHash,omitempty"`
	BlockHash            []byte   `protobuf:"bytes,4,opt,name=blockHash,proto3" json:"blockHash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DownloaderRequest) Reset()         { *m = DownloaderRequest{} }
func (m *DownloaderRequest) String() string { return proto.CompactTextString(m) }
func (*DownloaderRequest) ProtoMessage()    {}
func (*DownloaderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6a99ec95c7ab1ff1, []int{0}
}

func (m *DownloaderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DownloaderRequest.Unmarshal(m, b)
}
func (m *DownloaderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DownloaderRequest.Marshal(b, m, deterministic)
}
func (m *DownloaderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DownloaderRequest.Merge(m, src)
}
func (m *DownloaderRequest) XXX_Size() int {
	return xxx_messageInfo_DownloaderRequest.Size(m)
}
func (m *DownloaderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DownloaderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DownloaderRequest proto.InternalMessageInfo

func (m *DownloaderRequest) GetType() DownloaderRequest_RequestType {
	if m != nil {
		return m.Type
	}
	return DownloaderRequest_HEADER
}

func (m *DownloaderRequest) GetHashes() [][]byte {
	if m != nil {
		return m.Hashes
	}
	return nil
}

func (m *DownloaderRequest) GetPeerHash() []byte {
	if m != nil {
		return m.PeerHash
	}
	return nil
}

func (m *DownloaderRequest) GetBlockHash() []byte {
	if m != nil {
		return m.BlockHash
	}
	return nil
}

// DownloaderResponse is the generic response of DownloaderRequest.
type DownloaderResponse struct {
	// payload of Block.
	Payload [][]byte `protobuf:"bytes,1,rep,name=payload,proto3" json:"payload,omitempty"`
	// response of registration request
	Type                 DownloaderResponse_RegisterResponseType `protobuf:"varint,2,opt,name=type,proto3,enum=downloader.DownloaderResponse_RegisterResponseType" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                `json:"-"`
	XXX_unrecognized     []byte                                  `json:"-"`
	XXX_sizecache        int32                                   `json:"-"`
}

func (m *DownloaderResponse) Reset()         { *m = DownloaderResponse{} }
func (m *DownloaderResponse) String() string { return proto.CompactTextString(m) }
func (*DownloaderResponse) ProtoMessage()    {}
func (*DownloaderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6a99ec95c7ab1ff1, []int{1}
}

func (m *DownloaderResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DownloaderResponse.Unmarshal(m, b)
}
func (m *DownloaderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DownloaderResponse.Marshal(b, m, deterministic)
}
func (m *DownloaderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DownloaderResponse.Merge(m, src)
}
func (m *DownloaderResponse) XXX_Size() int {
	return xxx_messageInfo_DownloaderResponse.Size(m)
}
func (m *DownloaderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DownloaderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DownloaderResponse proto.InternalMessageInfo

func (m *DownloaderResponse) GetPayload() [][]byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *DownloaderResponse) GetType() DownloaderResponse_RegisterResponseType {
	if m != nil {
		return m.Type
	}
	return DownloaderResponse_SUCCESS
}

func init() {
	proto.RegisterEnum("downloader.DownloaderRequest_RequestType", DownloaderRequest_RequestType_name, DownloaderRequest_RequestType_value)
	proto.RegisterEnum("downloader.DownloaderResponse_RegisterResponseType", DownloaderResponse_RegisterResponseType_name, DownloaderResponse_RegisterResponseType_value)
	proto.RegisterType((*DownloaderRequest)(nil), "downloader.DownloaderRequest")
	proto.RegisterType((*DownloaderResponse)(nil), "downloader.DownloaderResponse")
}

func init() { proto.RegisterFile("downloader.proto", fileDescriptor_6a99ec95c7ab1ff1) }

var fileDescriptor_6a99ec95c7ab1ff1 = []byte{
	// 324 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x92, 0xcf, 0x4e, 0xc2, 0x40,
	0x10, 0xc6, 0xd9, 0x52, 0xfe, 0x0d, 0xc4, 0xac, 0x13, 0x63, 0x1a, 0xa2, 0x86, 0xf4, 0x84, 0x97,
	0x1e, 0xe0, 0xe4, 0xc1, 0x03, 0x96, 0x0a, 0x04, 0x52, 0xe2, 0x16, 0x24, 0x1e, 0x8b, 0x6c, 0xc4,
	0x48, 0xd8, 0xb5, 0x5b, 0x62, 0xfa, 0x5a, 0x3e, 0x9a, 0x4f, 0x60, 0xba, 0x20, 0x25, 0x51, 0x39,
	0x35, 0xbf, 0x6f, 0x3a, 0x33, 0xdf, 0x7e, 0xbb, 0x40, 0x17, 0xe2, 0x63, 0xbd, 0x12, 0xe1, 0x82,
	0x47, 0x8e, 0x8c, 0x44, 0x2c, 0x10, 0x32, 0xc5, 0xfe, 0x22, 0x70, 0xda, 0xdd, 0x23, 0xe3, 0xef,
	0x1b, 0xae, 0x62, 0xbc, 0x05, 0x33, 0x4e, 0x24, 0xb7, 0x48, 0x83, 0x34, 0x4f, 0x5a, 0xd7, 0xce,
	0xc1, 0x88, 0x5f, 0x3f, 0x3b, 0xbb, 0xef, 0x24, 0x91, 0x9c, 0xe9, 0x36, 0x3c, 0x87, 0xe2, 0x32,
	0x54, 0x4b, 0xae, 0x2c, 0xa3, 0x91, 0x6f, 0xd6, 0xd8, 0x8e, 0xb0, 0x0e, 0x65, 0xc9, 0x79, 0xd4,
	0x0f, 0xd5, 0xd2, 0xca, 0x37, 0x48, 0xb3, 0xc6, 0xf6, 0x8c, 0x17, 0x50, 0x99, 0xaf, 0xc4, 0xf3,
	0x9b, 0x2e, 0x9a, 0xba, 0x98, 0x09, 0xf6, 0x08, 0xaa, 0x07, 0x6b, 0x10, 0xa0, 0xd8, 0xf7, 0x3a,
	0x5d, 0x8f, 0xd1, 0x1c, 0x56, 0xa0, 0x70, 0x37, 0x1a, 0xbb, 0x43, 0x4a, 0xb0, 0x06, 0x65, 0xdf,
	0x9b, 0x6d, 0xc9, 0x48, 0x89, 0x79, 0xbd, 0x41, 0x30, 0xf1, 0x18, 0xcd, 0xa7, 0x2d, 0x53, 0x7f,
	0x38, 0x9e, 0xf9, 0xd4, 0xb4, 0x3f, 0x09, 0xe0, 0xe1, 0x39, 0x94, 0x14, 0x6b, 0xc5, 0xd1, 0x82,
	0x92, 0x0c, 0x93, 0x54, 0xb4, 0x88, 0xf6, 0xfd, 0x83, 0xd8, 0xdb, 0xe5, 0x61, 0xe8, 0x3c, 0xda,
	0xff, 0xe5, 0xb1, 0x9d, 0xe3, 0x30, 0xfe, 0xf2, 0xaa, 0xe2, 0x4c, 0xc8, 0x92, 0xb1, 0x6f, 0xe0,
	0xec, 0xaf, 0x2a, 0x56, 0xa1, 0x14, 0x4c, 0x5d, 0xd7, 0x0b, 0x02, 0x9a, 0xc3, 0x32, 0x98, 0xf7,
	0x9d, 0xc1, 0x88, 0x92, 0xd4, 0xf4, 0xc0, 0x0f, 0x9e, 0x7c, 0x97, 0x1a, 0xad, 0x47, 0x80, 0x6c,
	0x17, 0xf6, 0xa1, 0xf0, 0xb0, 0xe1, 0x51, 0x82, 0x97, 0x47, 0x2f, 0xa7, 0x7e, 0x75, 0xdc, 0xab,
	0x9d, 0x9b, 0x17, 0xf5, 0xa3, 0x68, 0x7f, 0x07, 0x00, 0x00, 0xff, 0xff, 0x01, 0xd7, 0x65, 0xa9,
	0x28, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DownloaderClient is the client API for Downloader service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DownloaderClient interface {
	Query(ctx context.Context, in *DownloaderRequest, opts ...grpc.CallOption) (*DownloaderResponse, error)
}

type downloaderClient struct {
	cc *grpc.ClientConn
}

func NewDownloaderClient(cc *grpc.ClientConn) DownloaderClient {
	return &downloaderClient{cc}
}

func (c *downloaderClient) Query(ctx context.Context, in *DownloaderRequest, opts ...grpc.CallOption) (*DownloaderResponse, error) {
	out := new(DownloaderResponse)
	err := c.cc.Invoke(ctx, "/downloader.Downloader/Query", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DownloaderServer is the server API for Downloader service.
type DownloaderServer interface {
	Query(context.Context, *DownloaderRequest) (*DownloaderResponse, error)
}

func RegisterDownloaderServer(s *grpc.Server, srv DownloaderServer) {
	s.RegisterService(&_Downloader_serviceDesc, srv)
}

func _Downloader_Query_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DownloaderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DownloaderServer).Query(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/downloader.Downloader/Query",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DownloaderServer).Query(ctx, req.(*DownloaderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Downloader_serviceDesc = grpc.ServiceDesc{
	ServiceName: "downloader.Downloader",
	HandlerType: (*DownloaderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Query",
			Handler:    _Downloader_Query_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "downloader.proto",
}
