// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

package message

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MessageType int32

const (
	MessageType_UNKNOWN          MessageType = 0
	MessageType_NEWNODE_BOOTNODE MessageType = 1
	MessageType_BOOTNODE_NEWNODE MessageType = 2
	MessageType_NEWNODE_BEACON   MessageType = 3
	MessageType_BEACON_NEWNODE   MessageType = 4
)

var MessageType_name = map[int32]string{
	0: "UNKNOWN",
	1: "NEWNODE_BOOTNODE",
	2: "BOOTNODE_NEWNODE",
	3: "NEWNODE_BEACON",
	4: "BEACON_NEWNODE",
}

var MessageType_value = map[string]int32{
	"UNKNOWN":          0,
	"NEWNODE_BOOTNODE": 1,
	"BOOTNODE_NEWNODE": 2,
	"NEWNODE_BEACON":   3,
	"BEACON_NEWNODE":   4,
}

func (x MessageType) String() string {
	return proto.EnumName(MessageType_name, int32(x))
}

func (MessageType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0}
}

// This is universal message for all communication protocols.
// There are different Requests for different message types.
// As we introduce a new type of message just add a new MessageType and new type of request in Message.
//
// The request field will be either one of the structure corresponding to the MessageType type.
type Message struct {
	Type MessageType `protobuf:"varint,1,opt,name=type,proto3,enum=message.MessageType" json:"type,omitempty"`
	// Types that are valid to be assigned to Request:
	//	*Message_NewnodeBootnodeRequest
	//	*Message_BootnodeNewnodeRequest
	Request              isMessage_Request `protobuf_oneof:"request"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetType() MessageType {
	if m != nil {
		return m.Type
	}
	return MessageType_UNKNOWN
}

type isMessage_Request interface {
	isMessage_Request()
}

type Message_NewnodeBootnodeRequest struct {
	NewnodeBootnodeRequest *NewNodeBootNodeRequest `protobuf:"bytes,2,opt,name=newnode_bootnode_request,json=newnodeBootnodeRequest,proto3,oneof"`
}

type Message_BootnodeNewnodeRequest struct {
	BootnodeNewnodeRequest *BootNodeNewNodeRequest `protobuf:"bytes,3,opt,name=bootnode_newnode_request,json=bootnodeNewnodeRequest,proto3,oneof"`
}

func (*Message_NewnodeBootnodeRequest) isMessage_Request() {}

func (*Message_BootnodeNewnodeRequest) isMessage_Request() {}

func (m *Message) GetRequest() isMessage_Request {
	if m != nil {
		return m.Request
	}
	return nil
}

func (m *Message) GetNewnodeBootnodeRequest() *NewNodeBootNodeRequest {
	if x, ok := m.GetRequest().(*Message_NewnodeBootnodeRequest); ok {
		return x.NewnodeBootnodeRequest
	}
	return nil
}

func (m *Message) GetBootnodeNewnodeRequest() *BootNodeNewNodeRequest {
	if x, ok := m.GetRequest().(*Message_BootnodeNewnodeRequest); ok {
		return x.BootnodeNewnodeRequest
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Message) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Message_NewnodeBootnodeRequest)(nil),
		(*Message_BootnodeNewnodeRequest)(nil),
	}
}

// Message of NewNode talking to BootNode.
type NewNodeBootNodeRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewNodeBootNodeRequest) Reset()         { *m = NewNodeBootNodeRequest{} }
func (m *NewNodeBootNodeRequest) String() string { return proto.CompactTextString(m) }
func (*NewNodeBootNodeRequest) ProtoMessage()    {}
func (*NewNodeBootNodeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{1}
}

func (m *NewNodeBootNodeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewNodeBootNodeRequest.Unmarshal(m, b)
}
func (m *NewNodeBootNodeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewNodeBootNodeRequest.Marshal(b, m, deterministic)
}
func (m *NewNodeBootNodeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewNodeBootNodeRequest.Merge(m, src)
}
func (m *NewNodeBootNodeRequest) XXX_Size() int {
	return xxx_messageInfo_NewNodeBootNodeRequest.Size(m)
}
func (m *NewNodeBootNodeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NewNodeBootNodeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NewNodeBootNodeRequest proto.InternalMessageInfo

// Message of BootNode talking to NewNode.
type BootNodeNewNodeRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BootNodeNewNodeRequest) Reset()         { *m = BootNodeNewNodeRequest{} }
func (m *BootNodeNewNodeRequest) String() string { return proto.CompactTextString(m) }
func (*BootNodeNewNodeRequest) ProtoMessage()    {}
func (*BootNodeNewNodeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{2}
}

func (m *BootNodeNewNodeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BootNodeNewNodeRequest.Unmarshal(m, b)
}
func (m *BootNodeNewNodeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BootNodeNewNodeRequest.Marshal(b, m, deterministic)
}
func (m *BootNodeNewNodeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BootNodeNewNodeRequest.Merge(m, src)
}
func (m *BootNodeNewNodeRequest) XXX_Size() int {
	return xxx_messageInfo_BootNodeNewNodeRequest.Size(m)
}
func (m *BootNodeNewNodeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BootNodeNewNodeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BootNodeNewNodeRequest proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("message.MessageType", MessageType_name, MessageType_value)
	proto.RegisterType((*Message)(nil), "message.Message")
	proto.RegisterType((*NewNodeBootNodeRequest)(nil), "message.NewNodeBootNodeRequest")
	proto.RegisterType((*BootNodeNewNodeRequest)(nil), "message.BootNodeNewNodeRequest")
}

func init() { proto.RegisterFile("message.proto", fileDescriptor_33c57e4bae7b9afd) }

var fileDescriptor_33c57e4bae7b9afd = []byte{
	// 253 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0x41, 0x4b, 0xc3, 0x40,
	0x10, 0x85, 0xbb, 0x6d, 0x31, 0x38, 0xc1, 0xb2, 0x2c, 0xa5, 0xe4, 0x66, 0xe9, 0x29, 0x78, 0xe8,
	0xa1, 0xfe, 0x02, 0xa3, 0x01, 0x41, 0x9c, 0x85, 0x50, 0xe9, 0xc1, 0x43, 0xb0, 0x74, 0xf0, 0x64,
	0x26, 0x36, 0x2b, 0xa5, 0xff, 0xdc, 0xa3, 0x6c, 0x32, 0x1b, 0x8a, 0xe4, 0xb4, 0x6f, 0xe6, 0xbd,
	0xf9, 0x66, 0xd9, 0x85, 0x9b, 0x2f, 0x6a, 0x9a, 0x8f, 0x4f, 0x5a, 0xd7, 0x47, 0x76, 0x6c, 0x22,
	0x29, 0x57, 0xbf, 0x0a, 0xa2, 0xd7, 0x4e, 0x9b, 0x14, 0xa6, 0xee, 0x5c, 0x53, 0xa2, 0x96, 0x2a,
	0x9d, 0x6d, 0xe6, 0xeb, 0x30, 0x22, 0xfe, 0xf6, 0x5c, 0x53, 0xd1, 0x26, 0xcc, 0x3b, 0x24, 0x15,
	0x9d, 0x2a, 0x3e, 0x50, 0xb9, 0x67, 0x76, 0xad, 0x38, 0xd2, 0xf7, 0x0f, 0x35, 0x2e, 0x19, 0x2f,
	0x55, 0x1a, 0x6f, 0x6e, 0xfb, 0x69, 0xa4, 0x13, 0xf2, 0x81, 0x32, 0x66, 0xe7, 0xcf, 0xa2, 0x8b,
	0x3d, 0x8f, 0x8a, 0x85, 0x20, 0x32, 0x21, 0x88, 0xe3, 0xe1, 0x3d, 0x34, 0x6c, 0x09, 0xf0, 0xc9,
	0x3f, 0x78, 0xa0, 0xca, 0x92, 0x0b, 0x78, 0x40, 0x60, 0x47, 0x10, 0x27, 0xbb, 0x86, 0x48, 0x58,
	0xab, 0x04, 0x16, 0xc3, 0x77, 0xf3, 0xce, 0x30, 0xf8, 0xae, 0x82, 0xf8, 0xe2, 0x35, 0x4c, 0x0c,
	0xd1, 0x1b, 0xbe, 0xa0, 0xdd, 0xa1, 0x1e, 0x99, 0x39, 0x68, 0xcc, 0x77, 0x68, 0x9f, 0xf2, 0x32,
	0xb3, 0x76, 0xeb, 0x85, 0x56, 0xbe, 0x1b, 0xaa, 0x52, 0x6c, 0x3d, 0x36, 0x06, 0x66, 0x7d, 0x36,
	0x7f, 0x78, 0xb4, 0xa8, 0x27, 0xbe, 0xd7, 0xe9, 0x3e, 0x37, 0xdd, 0x5f, 0xb5, 0xdf, 0x75, 0xff,
	0x17, 0x00, 0x00, 0xff, 0xff, 0x37, 0x30, 0xd0, 0xfb, 0xbf, 0x01, 0x00, 0x00,
}
