// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

package message

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MessageType int32

const (
	MessageType_UNKNOWN                MessageType = 0
	MessageType_NEWNODE_BOOTNODE       MessageType = 1
	MessageType_BOOTNODE_NEWNODE       MessageType = 2
	MessageType_NEWNODE_BEACON         MessageType = 3
	MessageType_BEACON_NEWNODE         MessageType = 4
	MessageType_NEWNODE_BEACON_STAKING MessageType = 5
)

var MessageType_name = map[int32]string{
	0: "UNKNOWN",
	1: "NEWNODE_BOOTNODE",
	2: "BOOTNODE_NEWNODE",
	3: "NEWNODE_BEACON",
	4: "BEACON_NEWNODE",
	5: "NEWNODE_BEACON_STAKING",
}

var MessageType_value = map[string]int32{
	"UNKNOWN":                0,
	"NEWNODE_BOOTNODE":       1,
	"BOOTNODE_NEWNODE":       2,
	"NEWNODE_BEACON":         3,
	"BEACON_NEWNODE":         4,
	"NEWNODE_BEACON_STAKING": 5,
}

func (x MessageType) String() string {
	return proto.EnumName(MessageType_name, int32(x))
}

func (MessageType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0}
}

// This is universal message for all communication protocols.
// There are different Requests for different message types.
// As we introduce a new type of message just add a new MessageType and new type of request in Message.
//
// The request field will be either one of the structure corresponding to the MessageType type.
type Message struct {
	Type MessageType `protobuf:"varint,1,opt,name=type,proto3,enum=message.MessageType" json:"type,omitempty"`
	// Types that are valid to be assigned to Request:
	//	*Message_Staking
	Request              isMessage_Request `protobuf_oneof:"request"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetType() MessageType {
	if m != nil {
		return m.Type
	}
	return MessageType_UNKNOWN
}

type isMessage_Request interface {
	isMessage_Request()
}

type Message_Staking struct {
	Staking *StakingRequest `protobuf:"bytes,3,opt,name=staking,proto3,oneof"`
}

func (*Message_Staking) isMessage_Request() {}

func (m *Message) GetRequest() isMessage_Request {
	if m != nil {
		return m.Request
	}
	return nil
}

func (m *Message) GetStaking() *StakingRequest {
	if x, ok := m.GetRequest().(*Message_Staking); ok {
		return x.Staking
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Message) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Message_Staking)(nil),
	}
}

// Message of NewNode talking to BootNode.
type NewNodeBootNodeRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewNodeBootNodeRequest) Reset()         { *m = NewNodeBootNodeRequest{} }
func (m *NewNodeBootNodeRequest) String() string { return proto.CompactTextString(m) }
func (*NewNodeBootNodeRequest) ProtoMessage()    {}
func (*NewNodeBootNodeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{1}
}

func (m *NewNodeBootNodeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewNodeBootNodeRequest.Unmarshal(m, b)
}
func (m *NewNodeBootNodeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewNodeBootNodeRequest.Marshal(b, m, deterministic)
}
func (m *NewNodeBootNodeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewNodeBootNodeRequest.Merge(m, src)
}
func (m *NewNodeBootNodeRequest) XXX_Size() int {
	return xxx_messageInfo_NewNodeBootNodeRequest.Size(m)
}
func (m *NewNodeBootNodeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NewNodeBootNodeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NewNodeBootNodeRequest proto.InternalMessageInfo

// Message of BootNode talking to NewNode.
type BootNodeNewNodeRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BootNodeNewNodeRequest) Reset()         { *m = BootNodeNewNodeRequest{} }
func (m *BootNodeNewNodeRequest) String() string { return proto.CompactTextString(m) }
func (*BootNodeNewNodeRequest) ProtoMessage()    {}
func (*BootNodeNewNodeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{2}
}

func (m *BootNodeNewNodeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BootNodeNewNodeRequest.Unmarshal(m, b)
}
func (m *BootNodeNewNodeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BootNodeNewNodeRequest.Marshal(b, m, deterministic)
}
func (m *BootNodeNewNodeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BootNodeNewNodeRequest.Merge(m, src)
}
func (m *BootNodeNewNodeRequest) XXX_Size() int {
	return xxx_messageInfo_BootNodeNewNodeRequest.Size(m)
}
func (m *BootNodeNewNodeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BootNodeNewNodeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BootNodeNewNodeRequest proto.InternalMessageInfo

// Staking Request from new node to beacon node.
type StakingRequest struct {
	Transaction          []byte   `protobuf:"bytes,1,opt,name=transaction,proto3" json:"transaction,omitempty"`
	NodeId               string   `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StakingRequest) Reset()         { *m = StakingRequest{} }
func (m *StakingRequest) String() string { return proto.CompactTextString(m) }
func (*StakingRequest) ProtoMessage()    {}
func (*StakingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{3}
}

func (m *StakingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StakingRequest.Unmarshal(m, b)
}
func (m *StakingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StakingRequest.Marshal(b, m, deterministic)
}
func (m *StakingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StakingRequest.Merge(m, src)
}
func (m *StakingRequest) XXX_Size() int {
	return xxx_messageInfo_StakingRequest.Size(m)
}
func (m *StakingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StakingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StakingRequest proto.InternalMessageInfo

func (m *StakingRequest) GetTransaction() []byte {
	if m != nil {
		return m.Transaction
	}
	return nil
}

func (m *StakingRequest) GetNodeId() string {
	if m != nil {
		return m.NodeId
	}
	return ""
}

func init() {
	proto.RegisterEnum("message.MessageType", MessageType_name, MessageType_value)
	proto.RegisterType((*Message)(nil), "message.Message")
	proto.RegisterType((*NewNodeBootNodeRequest)(nil), "message.NewNodeBootNodeRequest")
	proto.RegisterType((*BootNodeNewNodeRequest)(nil), "message.BootNodeNewNodeRequest")
	proto.RegisterType((*StakingRequest)(nil), "message.StakingRequest")
}

func init() { proto.RegisterFile("message.proto", fileDescriptor_33c57e4bae7b9afd) }

var fileDescriptor_33c57e4bae7b9afd = []byte{
	// 276 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x91, 0x4f, 0x6b, 0xc2, 0x30,
	0x18, 0xc6, 0x8d, 0x3a, 0x83, 0x6f, 0xb7, 0x12, 0x82, 0x68, 0xd9, 0xa9, 0x78, 0x2a, 0x3b, 0x78,
	0xd0, 0x4f, 0x60, 0xb7, 0xb2, 0x49, 0x59, 0x0a, 0xb1, 0xc3, 0x63, 0xe9, 0xd6, 0x20, 0x65, 0xac,
	0xe9, 0x9a, 0x8c, 0xe1, 0x57, 0xd8, 0xa7, 0x1e, 0xfd, 0x93, 0xaa, 0xa7, 0xbc, 0xcf, 0xef, 0xf9,
	0x25, 0x24, 0x04, 0xee, 0xbe, 0x84, 0x52, 0xe9, 0x51, 0xac, 0xca, 0x4a, 0x6a, 0x49, 0x71, 0x17,
	0x97, 0x0a, 0xf0, 0x6b, 0x3b, 0x52, 0x0f, 0xc6, 0xfa, 0x54, 0x0a, 0x07, 0xb9, 0xc8, 0xb3, 0xd7,
	0xb3, 0x95, 0xd9, 0xd1, 0xf5, 0xf1, 0xa9, 0x14, 0xbc, 0x31, 0xe8, 0x06, 0xb0, 0xd2, 0xe9, 0x67,
	0x5e, 0x1c, 0x9d, 0x91, 0x8b, 0x3c, 0x6b, 0xbd, 0xe8, 0xe5, 0x7d, 0xcb, 0xb9, 0xf8, 0xfe, 0x11,
	0x4a, 0xbf, 0x0c, 0xb8, 0x31, 0xfd, 0x29, 0xe0, 0xaa, 0xa5, 0x4b, 0x07, 0xe6, 0x4c, 0xfc, 0x32,
	0x99, 0x09, 0x5f, 0x4a, 0x5d, 0xaf, 0xfc, 0xdc, 0x18, 0xd4, 0x19, 0xa6, 0x09, 0xc1, 0xbe, 0x3e,
	0x9b, 0xba, 0x60, 0xe9, 0x2a, 0x2d, 0x54, 0xfa, 0xa1, 0x73, 0x59, 0x34, 0xd7, 0xbe, 0xe5, 0x97,
	0x88, 0x2e, 0x00, 0x17, 0x32, 0x13, 0x49, 0x9e, 0x39, 0x43, 0x17, 0x79, 0x53, 0x3e, 0xa9, 0xe3,
	0x2e, 0x7b, 0xf8, 0x43, 0x60, 0x5d, 0x3c, 0x8b, 0x5a, 0x80, 0xdf, 0x58, 0xc8, 0xa2, 0x03, 0x23,
	0x03, 0x3a, 0x03, 0xc2, 0x82, 0x03, 0x8b, 0x9e, 0x82, 0xc4, 0x8f, 0xa2, 0xb8, 0x1e, 0x08, 0xaa,
	0xa9, 0x49, 0x49, 0x57, 0x93, 0x21, 0xa5, 0x60, 0xf7, 0x6e, 0xb0, 0x7d, 0x8c, 0x18, 0x19, 0xd5,
	0xac, 0x9d, 0x7b, 0x6f, 0x4c, 0xef, 0x61, 0x7e, 0xed, 0x25, 0xfb, 0x78, 0x1b, 0xee, 0xd8, 0x33,
	0xb9, 0x79, 0x9f, 0x34, 0x5f, 0xb2, 0xf9, 0x0f, 0x00, 0x00, 0xff, 0xff, 0x1b, 0xd6, 0xe4, 0x08,
	0xa3, 0x01, 0x00, 0x00,
}
