// Code generated by protoc-gen-go. DO NOT EDIT.
// source: beaconchain.proto

package beaconchain

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// FetchLeadersRequest is the request to fetch the current leaders.
type FetchLeadersRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FetchLeadersRequest) Reset()         { *m = FetchLeadersRequest{} }
func (m *FetchLeadersRequest) String() string { return proto.CompactTextString(m) }
func (*FetchLeadersRequest) ProtoMessage()    {}
func (*FetchLeadersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_474fd8061d1037cf, []int{0}
}

func (m *FetchLeadersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FetchLeadersRequest.Unmarshal(m, b)
}
func (m *FetchLeadersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FetchLeadersRequest.Marshal(b, m, deterministic)
}
func (m *FetchLeadersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FetchLeadersRequest.Merge(m, src)
}
func (m *FetchLeadersRequest) XXX_Size() int {
	return xxx_messageInfo_FetchLeadersRequest.Size(m)
}
func (m *FetchLeadersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FetchLeadersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FetchLeadersRequest proto.InternalMessageInfo

// FetchLeadersResponse is the response of FetchLeadersRequest.
type FetchLeadersResponse struct {
	Leaders              []*FetchLeadersResponse_Leader `protobuf:"bytes,1,rep,name=leaders,proto3" json:"leaders,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *FetchLeadersResponse) Reset()         { *m = FetchLeadersResponse{} }
func (m *FetchLeadersResponse) String() string { return proto.CompactTextString(m) }
func (*FetchLeadersResponse) ProtoMessage()    {}
func (*FetchLeadersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_474fd8061d1037cf, []int{1}
}

func (m *FetchLeadersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FetchLeadersResponse.Unmarshal(m, b)
}
func (m *FetchLeadersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FetchLeadersResponse.Marshal(b, m, deterministic)
}
func (m *FetchLeadersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FetchLeadersResponse.Merge(m, src)
}
func (m *FetchLeadersResponse) XXX_Size() int {
	return xxx_messageInfo_FetchLeadersResponse.Size(m)
}
func (m *FetchLeadersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FetchLeadersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FetchLeadersResponse proto.InternalMessageInfo

func (m *FetchLeadersResponse) GetLeaders() []*FetchLeadersResponse_Leader {
	if m != nil {
		return m.Leaders
	}
	return nil
}

type FetchLeadersResponse_Leader struct {
	Ip                   string   `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Port                 string   `protobuf:"bytes,2,opt,name=port,proto3" json:"port,omitempty"`
	ShardId              uint32   `protobuf:"varint,3,opt,name=shardId,proto3" json:"shardId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FetchLeadersResponse_Leader) Reset()         { *m = FetchLeadersResponse_Leader{} }
func (m *FetchLeadersResponse_Leader) String() string { return proto.CompactTextString(m) }
func (*FetchLeadersResponse_Leader) ProtoMessage()    {}
func (*FetchLeadersResponse_Leader) Descriptor() ([]byte, []int) {
	return fileDescriptor_474fd8061d1037cf, []int{1, 0}
}

func (m *FetchLeadersResponse_Leader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FetchLeadersResponse_Leader.Unmarshal(m, b)
}
func (m *FetchLeadersResponse_Leader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FetchLeadersResponse_Leader.Marshal(b, m, deterministic)
}
func (m *FetchLeadersResponse_Leader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FetchLeadersResponse_Leader.Merge(m, src)
}
func (m *FetchLeadersResponse_Leader) XXX_Size() int {
	return xxx_messageInfo_FetchLeadersResponse_Leader.Size(m)
}
func (m *FetchLeadersResponse_Leader) XXX_DiscardUnknown() {
	xxx_messageInfo_FetchLeadersResponse_Leader.DiscardUnknown(m)
}

var xxx_messageInfo_FetchLeadersResponse_Leader proto.InternalMessageInfo

func (m *FetchLeadersResponse_Leader) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *FetchLeadersResponse_Leader) GetPort() string {
	if m != nil {
		return m.Port
	}
	return ""
}

func (m *FetchLeadersResponse_Leader) GetShardId() uint32 {
	if m != nil {
		return m.ShardId
	}
	return 0
}

//HelloRequest is to request hello beaconchain
type HelloRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloRequest) Reset()         { *m = HelloRequest{} }
func (m *HelloRequest) String() string { return proto.CompactTextString(m) }
func (*HelloRequest) ProtoMessage()    {}
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_474fd8061d1037cf, []int{2}
}

func (m *HelloRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloRequest.Unmarshal(m, b)
}
func (m *HelloRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloRequest.Marshal(b, m, deterministic)
}
func (m *HelloRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloRequest.Merge(m, src)
}
func (m *HelloRequest) XXX_Size() int {
	return xxx_messageInfo_HelloRequest.Size(m)
}
func (m *HelloRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HelloRequest proto.InternalMessageInfo

//HelloResponse is a response "hello" from beaconchain
type HelloResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloResponse) Reset()         { *m = HelloResponse{} }
func (m *HelloResponse) String() string { return proto.CompactTextString(m) }
func (*HelloResponse) ProtoMessage()    {}
func (*HelloResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_474fd8061d1037cf, []int{3}
}

func (m *HelloResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloResponse.Unmarshal(m, b)
}
func (m *HelloResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloResponse.Marshal(b, m, deterministic)
}
func (m *HelloResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloResponse.Merge(m, src)
}
func (m *HelloResponse) XXX_Size() int {
	return xxx_messageInfo_HelloResponse.Size(m)
}
func (m *HelloResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HelloResponse proto.InternalMessageInfo

func (m *HelloResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*FetchLeadersRequest)(nil), "beaconchain.FetchLeadersRequest")
	proto.RegisterType((*FetchLeadersResponse)(nil), "beaconchain.FetchLeadersResponse")
	proto.RegisterType((*FetchLeadersResponse_Leader)(nil), "beaconchain.FetchLeadersResponse.Leader")
	proto.RegisterType((*HelloRequest)(nil), "beaconchain.HelloRequest")
	proto.RegisterType((*HelloResponse)(nil), "beaconchain.HelloResponse")
}

func init() { proto.RegisterFile("beaconchain.proto", fileDescriptor_474fd8061d1037cf) }

var fileDescriptor_474fd8061d1037cf = []byte{
	// 258 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x91, 0xdf, 0x4a, 0xc3, 0x30,
	0x18, 0xc5, 0x4d, 0x27, 0xab, 0x7e, 0xfb, 0x03, 0x7e, 0x2a, 0xc4, 0x5e, 0xd5, 0x5e, 0xd5, 0x9b,
	0x5e, 0xcc, 0x37, 0xd8, 0x60, 0x28, 0x78, 0xd5, 0xe1, 0x03, 0x64, 0xed, 0x87, 0x2d, 0xd4, 0x26,
	0x26, 0x51, 0xf0, 0x75, 0x7c, 0x02, 0x1f, 0x51, 0x4c, 0x1b, 0xc8, 0x60, 0xe8, 0x5d, 0xce, 0x09,
	0x27, 0xe7, 0x77, 0x08, 0x5c, 0xec, 0x49, 0x54, 0xb2, 0xaf, 0x1a, 0xd1, 0xf6, 0x85, 0xd2, 0xd2,
	0x4a, 0x9c, 0x05, 0x56, 0x76, 0x0d, 0x97, 0x5b, 0xb2, 0x55, 0xf3, 0x44, 0xa2, 0x26, 0x6d, 0x4a,
	0x7a, 0x7b, 0x27, 0x63, 0xb3, 0x2f, 0x06, 0x57, 0x87, 0xbe, 0x51, 0xb2, 0x37, 0x84, 0x6b, 0x88,
	0xbb, 0xc1, 0xe2, 0x2c, 0x9d, 0xe4, 0xb3, 0x55, 0x5e, 0x84, 0x0d, 0xc7, 0x32, 0xc5, 0xa0, 0x4b,
	0x1f, 0x4c, 0xb6, 0x30, 0x1d, 0x2c, 0x5c, 0x42, 0xd4, 0x2a, 0xce, 0x52, 0x96, 0x9f, 0x97, 0x51,
	0xab, 0x10, 0xe1, 0x54, 0x49, 0x6d, 0x79, 0xe4, 0x1c, 0x77, 0x46, 0x0e, 0xb1, 0x69, 0x84, 0xae,
	0x1f, 0x6b, 0x3e, 0x49, 0x59, 0xbe, 0x28, 0xbd, 0xcc, 0x96, 0x30, 0x7f, 0xa0, 0xae, 0x93, 0x1e,
	0xfa, 0x0e, 0x16, 0xa3, 0x1e, 0x61, 0x39, 0xc4, 0xaf, 0x64, 0x8c, 0x78, 0xa1, 0xb1, 0xc3, 0xcb,
	0xd5, 0x37, 0x03, 0x5c, 0x3b, 0xee, 0xcd, 0x2f, 0xf7, 0x8e, 0xf4, 0x47, 0x5b, 0x11, 0x3e, 0xc3,
	0x3c, 0x5c, 0x80, 0xe9, 0x1f, 0xe3, 0x5c, 0x67, 0x72, 0xfb, 0xef, 0xfc, 0xec, 0x04, 0x37, 0x70,
	0xb6, 0x13, 0x9f, 0x8e, 0x0d, 0x6f, 0x0e, 0x02, 0x21, 0x7f, 0x92, 0x1c, 0xbb, 0xf2, 0x8f, 0xec,
	0xa7, 0xee, 0xf7, 0xee, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0x94, 0xb2, 0x9c, 0xa3, 0xd2, 0x01,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// BeaconChainServiceClient is the client API for BeaconChainService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BeaconChainServiceClient interface {
	FetchLeaders(ctx context.Context, in *FetchLeadersRequest, opts ...grpc.CallOption) (*FetchLeadersResponse, error)
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error)
}

type beaconChainServiceClient struct {
	cc *grpc.ClientConn
}

func NewBeaconChainServiceClient(cc *grpc.ClientConn) BeaconChainServiceClient {
	return &beaconChainServiceClient{cc}
}

func (c *beaconChainServiceClient) FetchLeaders(ctx context.Context, in *FetchLeadersRequest, opts ...grpc.CallOption) (*FetchLeadersResponse, error) {
	out := new(FetchLeadersResponse)
	err := c.cc.Invoke(ctx, "/beaconchain.BeaconChainService/FetchLeaders", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *beaconChainServiceClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error) {
	out := new(HelloResponse)
	err := c.cc.Invoke(ctx, "/beaconchain.BeaconChainService/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BeaconChainServiceServer is the server API for BeaconChainService service.
type BeaconChainServiceServer interface {
	FetchLeaders(context.Context, *FetchLeadersRequest) (*FetchLeadersResponse, error)
	SayHello(context.Context, *HelloRequest) (*HelloResponse, error)
}

func RegisterBeaconChainServiceServer(s *grpc.Server, srv BeaconChainServiceServer) {
	s.RegisterService(&_BeaconChainService_serviceDesc, srv)
}

func _BeaconChainService_FetchLeaders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchLeadersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BeaconChainServiceServer).FetchLeaders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/beaconchain.BeaconChainService/FetchLeaders",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BeaconChainServiceServer).FetchLeaders(ctx, req.(*FetchLeadersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BeaconChainService_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BeaconChainServiceServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/beaconchain.BeaconChainService/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BeaconChainServiceServer).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _BeaconChainService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "beaconchain.BeaconChainService",
	HandlerType: (*BeaconChainServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FetchLeaders",
			Handler:    _BeaconChainService_FetchLeaders_Handler,
		},
		{
			MethodName: "SayHello",
			Handler:    _BeaconChainService_SayHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "beaconchain.proto",
}
