// Code generated by protoc-gen-go. DO NOT EDIT.
// source: monitoringservice.proto

package monitoringservice

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MetricsType int32

const (
	MetricsType_CONNECTIONS_STATS MetricsType = 0
)

var MetricsType_name = map[int32]string{
	0: "CONNECTIONS_STATS",
}

var MetricsType_value = map[string]int32{
	"CONNECTIONS_STATS": 0,
}

func (x MetricsType) String() string {
	return proto.EnumName(MetricsType_name, int32(x))
}

func (MetricsType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_9b849e0e333a202a, []int{0}
}

type ConnectionsStats struct {
	Time                 int32    `protobuf:"varint,1,opt,name=time,proto3" json:"time,omitempty"`
	ConnectionsNumber    int32    `protobuf:"varint,2,opt,name=connections_number,json=connectionsNumber,proto3" json:"connections_number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConnectionsStats) Reset()         { *m = ConnectionsStats{} }
func (m *ConnectionsStats) String() string { return proto.CompactTextString(m) }
func (*ConnectionsStats) ProtoMessage()    {}
func (*ConnectionsStats) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b849e0e333a202a, []int{0}
}

func (m *ConnectionsStats) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConnectionsStats.Unmarshal(m, b)
}
func (m *ConnectionsStats) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConnectionsStats.Marshal(b, m, deterministic)
}
func (m *ConnectionsStats) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConnectionsStats.Merge(m, src)
}
func (m *ConnectionsStats) XXX_Size() int {
	return xxx_messageInfo_ConnectionsStats.Size(m)
}
func (m *ConnectionsStats) XXX_DiscardUnknown() {
	xxx_messageInfo_ConnectionsStats.DiscardUnknown(m)
}

var xxx_messageInfo_ConnectionsStats proto.InternalMessageInfo

func (m *ConnectionsStats) GetTime() int32 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *ConnectionsStats) GetConnectionsNumber() int32 {
	if m != nil {
		return m.ConnectionsNumber
	}
	return 0
}

type ConnectionsStatsRequest struct {
	Since                int32    `protobuf:"varint,1,opt,name=since,proto3" json:"since,omitempty"`
	Until                int32    `protobuf:"varint,2,opt,name=until,proto3" json:"until,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConnectionsStatsRequest) Reset()         { *m = ConnectionsStatsRequest{} }
func (m *ConnectionsStatsRequest) String() string { return proto.CompactTextString(m) }
func (*ConnectionsStatsRequest) ProtoMessage()    {}
func (*ConnectionsStatsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b849e0e333a202a, []int{1}
}

func (m *ConnectionsStatsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConnectionsStatsRequest.Unmarshal(m, b)
}
func (m *ConnectionsStatsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConnectionsStatsRequest.Marshal(b, m, deterministic)
}
func (m *ConnectionsStatsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConnectionsStatsRequest.Merge(m, src)
}
func (m *ConnectionsStatsRequest) XXX_Size() int {
	return xxx_messageInfo_ConnectionsStatsRequest.Size(m)
}
func (m *ConnectionsStatsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ConnectionsStatsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ConnectionsStatsRequest proto.InternalMessageInfo

func (m *ConnectionsStatsRequest) GetSince() int32 {
	if m != nil {
		return m.Since
	}
	return 0
}

func (m *ConnectionsStatsRequest) GetUntil() int32 {
	if m != nil {
		return m.Until
	}
	return 0
}

type ConnectionsStatsResponse struct {
	ConnectionsStats     []*ConnectionsStats `protobuf:"bytes,1,rep,name=connections_stats,json=connectionsStats,proto3" json:"connections_stats,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *ConnectionsStatsResponse) Reset()         { *m = ConnectionsStatsResponse{} }
func (m *ConnectionsStatsResponse) String() string { return proto.CompactTextString(m) }
func (*ConnectionsStatsResponse) ProtoMessage()    {}
func (*ConnectionsStatsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b849e0e333a202a, []int{2}
}

func (m *ConnectionsStatsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConnectionsStatsResponse.Unmarshal(m, b)
}
func (m *ConnectionsStatsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConnectionsStatsResponse.Marshal(b, m, deterministic)
}
func (m *ConnectionsStatsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConnectionsStatsResponse.Merge(m, src)
}
func (m *ConnectionsStatsResponse) XXX_Size() int {
	return xxx_messageInfo_ConnectionsStatsResponse.Size(m)
}
func (m *ConnectionsStatsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ConnectionsStatsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ConnectionsStatsResponse proto.InternalMessageInfo

func (m *ConnectionsStatsResponse) GetConnectionsStats() []*ConnectionsStats {
	if m != nil {
		return m.ConnectionsStats
	}
	return nil
}

type Request struct {
	MetricsType MetricsType `protobuf:"varint,1,opt,name=metrics_type,json=metricsType,proto3,enum=monitoringservice.MetricsType" json:"metrics_type,omitempty"`
	// Types that are valid to be assigned to Request:
	//	*Request_ConnectionsStatsRequest
	Request              isRequest_Request `protobuf_oneof:"request"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b849e0e333a202a, []int{3}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetMetricsType() MetricsType {
	if m != nil {
		return m.MetricsType
	}
	return MetricsType_CONNECTIONS_STATS
}

type isRequest_Request interface {
	isRequest_Request()
}

type Request_ConnectionsStatsRequest struct {
	ConnectionsStatsRequest *ConnectionsStatsRequest `protobuf:"bytes,2,opt,name=connections_stats_request,json=connectionsStatsRequest,proto3,oneof"`
}

func (*Request_ConnectionsStatsRequest) isRequest_Request() {}

func (m *Request) GetRequest() isRequest_Request {
	if m != nil {
		return m.Request
	}
	return nil
}

func (m *Request) GetConnectionsStatsRequest() *ConnectionsStatsRequest {
	if x, ok := m.GetRequest().(*Request_ConnectionsStatsRequest); ok {
		return x.ConnectionsStatsRequest
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Request) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Request_ConnectionsStatsRequest)(nil),
	}
}

type Response struct {
	MetricsType MetricsType `protobuf:"varint,1,opt,name=metrics_type,json=metricsType,proto3,enum=monitoringservice.MetricsType" json:"metrics_type,omitempty"`
	// Types that are valid to be assigned to Response:
	//	*Response_ConnectionsStatsResponse
	Response             isResponse_Response `protobuf_oneof:"response"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b849e0e333a202a, []int{4}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetMetricsType() MetricsType {
	if m != nil {
		return m.MetricsType
	}
	return MetricsType_CONNECTIONS_STATS
}

type isResponse_Response interface {
	isResponse_Response()
}

type Response_ConnectionsStatsResponse struct {
	ConnectionsStatsResponse *ConnectionsStatsResponse `protobuf:"bytes,2,opt,name=connections_stats_response,json=connectionsStatsResponse,proto3,oneof"`
}

func (*Response_ConnectionsStatsResponse) isResponse_Response() {}

func (m *Response) GetResponse() isResponse_Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (m *Response) GetConnectionsStatsResponse() *ConnectionsStatsResponse {
	if x, ok := m.GetResponse().(*Response_ConnectionsStatsResponse); ok {
		return x.ConnectionsStatsResponse
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Response) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Response_ConnectionsStatsResponse)(nil),
	}
}

func init() {
	proto.RegisterEnum("monitoringservice.MetricsType", MetricsType_name, MetricsType_value)
	proto.RegisterType((*ConnectionsStats)(nil), "monitoringservice.ConnectionsStats")
	proto.RegisterType((*ConnectionsStatsRequest)(nil), "monitoringservice.ConnectionsStatsRequest")
	proto.RegisterType((*ConnectionsStatsResponse)(nil), "monitoringservice.ConnectionsStatsResponse")
	proto.RegisterType((*Request)(nil), "monitoringservice.Request")
	proto.RegisterType((*Response)(nil), "monitoringservice.Response")
}

func init() { proto.RegisterFile("monitoringservice.proto", fileDescriptor_9b849e0e333a202a) }

var fileDescriptor_9b849e0e333a202a = []byte{
	// 360 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x93, 0xc1, 0x4e, 0xfa, 0x40,
	0x10, 0xc6, 0xdb, 0xff, 0x5f, 0x04, 0xa7, 0x6a, 0x60, 0xa3, 0xa1, 0x62, 0x62, 0x48, 0xf5, 0x40,
	0x30, 0x72, 0xa8, 0x4f, 0x00, 0x95, 0x04, 0x0f, 0x16, 0xd2, 0x96, 0x73, 0x23, 0x9b, 0x8d, 0x6e,
	0xa4, 0xbb, 0x75, 0x77, 0x31, 0xe1, 0xf1, 0xbc, 0xf8, 0x5c, 0x86, 0x6e, 0x11, 0x42, 0x6b, 0xc2,
	0xc1, 0x5b, 0x67, 0xbf, 0x99, 0xdf, 0x7c, 0xdf, 0x24, 0x85, 0x66, 0xc2, 0x19, 0x55, 0x5c, 0x50,
	0xf6, 0x22, 0x89, 0xf8, 0xa0, 0x98, 0xf4, 0x52, 0xc1, 0x15, 0x47, 0x8d, 0x82, 0xe0, 0x4c, 0xa1,
	0xee, 0x71, 0xc6, 0x08, 0x56, 0x94, 0x33, 0x19, 0xaa, 0x67, 0x25, 0x11, 0x82, 0x03, 0x45, 0x13,
	0x62, 0x9b, 0x6d, 0xb3, 0x53, 0x09, 0xb2, 0x6f, 0x74, 0x07, 0x08, 0x6f, 0xfa, 0x62, 0xb6, 0x48,
	0x66, 0x44, 0xd8, 0xff, 0xb2, 0x8e, 0xc6, 0x96, 0xe2, 0x67, 0x82, 0x33, 0x84, 0xe6, 0x2e, 0x36,
	0x20, 0xef, 0x0b, 0x22, 0x15, 0x3a, 0x83, 0x8a, 0xa4, 0x0c, 0xaf, 0xf1, 0xba, 0x58, 0xbd, 0x2e,
	0x98, 0xa2, 0xf3, 0x1c, 0xa9, 0x0b, 0x67, 0x0e, 0x76, 0x11, 0x23, 0x53, 0xce, 0x24, 0x41, 0x13,
	0xd8, 0xde, 0x1b, 0xcb, 0x95, 0x68, 0x9b, 0xed, 0xff, 0x1d, 0xcb, 0xbd, 0xee, 0x15, 0x2f, 0x50,
	0xe0, 0xd4, 0xf1, 0xce, 0x8b, 0xf3, 0x69, 0x42, 0x75, 0xed, 0xb2, 0x0f, 0xc7, 0x09, 0x51, 0x82,
	0x62, 0x19, 0xab, 0x65, 0xaa, 0xcd, 0x9e, 0xba, 0x57, 0x25, 0xe0, 0x27, 0xdd, 0x16, 0x2d, 0x53,
	0x12, 0x58, 0xc9, 0xa6, 0x40, 0xaf, 0x70, 0x51, 0x30, 0x18, 0x0b, 0xcd, 0xcf, 0x62, 0x5a, 0x6e,
	0x77, 0x1f, 0xa3, 0x7a, 0x62, 0x64, 0x04, 0x4d, 0x5c, 0x2e, 0x0d, 0x8e, 0xa0, 0x9a, 0x73, 0x9d,
	0x2f, 0x13, 0x6a, 0x3f, 0x27, 0xfa, 0x83, 0x10, 0x6f, 0xd0, 0x2a, 0x0b, 0xa1, 0x17, 0xe4, 0x29,
	0x6e, 0xf7, 0x4a, 0xa1, 0x47, 0x46, 0x46, 0x60, 0xe3, 0x5f, 0xb4, 0x01, 0x40, 0x6d, 0x8d, 0xee,
	0xde, 0x80, 0xb5, 0x65, 0x0a, 0x9d, 0x43, 0xc3, 0x1b, 0xfb, 0xfe, 0xd0, 0x8b, 0x1e, 0xc7, 0x7e,
	0x18, 0x87, 0x51, 0x3f, 0x0a, 0xeb, 0x86, 0x3b, 0x85, 0x13, 0x6f, 0x4e, 0x09, 0x53, 0xa1, 0xde,
	0x8b, 0x1e, 0xa0, 0x3a, 0x11, 0x1c, 0x13, 0x29, 0x51, 0xab, 0xc4, 0x56, 0x7e, 0xb1, 0xd6, 0x65,
	0xa9, 0xa6, 0x57, 0x3b, 0xc6, 0xec, 0x30, 0xfb, 0x5f, 0xee, 0xbf, 0x03, 0x00, 0x00, 0xff, 0xff,
	0x2b, 0x82, 0x28, 0x8c, 0x4a, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ClientServiceClient is the client API for ClientService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ClientServiceClient interface {
	Process(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type clientServiceClient struct {
	cc *grpc.ClientConn
}

func NewClientServiceClient(cc *grpc.ClientConn) ClientServiceClient {
	return &clientServiceClient{cc}
}

func (c *clientServiceClient) Process(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/monitoringservice.ClientService/Process", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ClientServiceServer is the server API for ClientService service.
type ClientServiceServer interface {
	Process(context.Context, *Request) (*Response, error)
}

// UnimplementedClientServiceServer can be embedded to have forward compatible implementations.
type UnimplementedClientServiceServer struct {
}

func (*UnimplementedClientServiceServer) Process(ctx context.Context, req *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Process not implemented")
}

func RegisterClientServiceServer(s *grpc.Server, srv ClientServiceServer) {
	s.RegisterService(&_ClientService_serviceDesc, srv)
}

func _ClientService_Process_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientServiceServer).Process(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/monitoringservice.ClientService/Process",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientServiceServer).Process(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

var _ClientService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "monitoringservice.ClientService",
	HandlerType: (*ClientServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Process",
			Handler:    _ClientService_Process_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "monitoringservice.proto",
}
