// Package integrity implements the plain SHA-256 integrity layer (plan
// §4.7, no signatures): sha256sum-compatible checksum files and their
// verification. Two tiers use it: (a) internal run checksums written by
// export-reference over its own outputs, and (b) the release SHA256SUMS
// regenerated by the final sealing step over exactly the four release
// files.
package integrity

import (
	"bufio"
	"crypto/sha256"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// FileSHA256Hex streams path through SHA-256.
func FileSHA256Hex(path string) (string, error) {
	f, err := os.Open(path)
	if err != nil {
		return "", err
	}
	defer f.Close()
	h := sha256.New()
	if _, err := io.Copy(h, f); err != nil {
		return "", err
	}
	return fmt.Sprintf("%x", h.Sum(nil)), nil
}

// Entry is one checksum line.
type Entry struct {
	SHA256Hex string
	Name      string // base name, relative to the checksum file's directory
}

// Format renders entries in the exact `sha256sum` output format
// ("<hex>  <name>\n", two spaces), sorted by name for determinism.
func Format(entries []Entry) []byte {
	sorted := append([]Entry(nil), entries...)
	sort.Slice(sorted, func(i, j int) bool { return sorted[i].Name < sorted[j].Name })
	var b strings.Builder
	for _, e := range sorted {
		fmt.Fprintf(&b, "%s  %s\n", e.SHA256Hex, e.Name)
	}
	return []byte(b.String())
}

// WriteSums regenerates (never appends) the checksum file at sumsPath over
// exactly the named files (paths relative to the sums file's directory).
func WriteSums(sumsPath string, names []string) error {
	dir := filepath.Dir(sumsPath)
	entries := make([]Entry, 0, len(names))
	for _, name := range names {
		hex, err := FileSHA256Hex(filepath.Join(dir, name))
		if err != nil {
			return fmt.Errorf("integrity: hash %s: %w", name, err)
		}
		entries = append(entries, Entry{SHA256Hex: hex, Name: name})
	}
	return os.WriteFile(sumsPath, Format(entries), 0o644)
}

// Parse reads a sha256sum-format file.
func Parse(sumsPath string) ([]Entry, error) {
	f, err := os.Open(sumsPath)
	if err != nil {
		return nil, err
	}
	defer f.Close()
	var entries []Entry
	sc := bufio.NewScanner(f)
	for sc.Scan() {
		line := sc.Text()
		if strings.TrimSpace(line) == "" {
			continue
		}
		// "<hex><space><space or *><name>"
		if len(line) < 66 {
			return nil, fmt.Errorf("integrity: malformed line %q", line)
		}
		hex, rest := line[:64], line[64:]
		if !strings.HasPrefix(rest, "  ") && !strings.HasPrefix(rest, " *") {
			return nil, fmt.Errorf("integrity: malformed separator in %q", line)
		}
		entries = append(entries, Entry{SHA256Hex: strings.ToLower(hex), Name: rest[2:]})
	}
	if err := sc.Err(); err != nil {
		return nil, err
	}
	return entries, nil
}

// Verify checks every entry in the sums file against the files next to it
// (the `sha256sum -c` behavior).
func Verify(sumsPath string) error {
	entries, err := Parse(sumsPath)
	if err != nil {
		return err
	}
	dir := filepath.Dir(sumsPath)
	for _, e := range entries {
		got, err := FileSHA256Hex(filepath.Join(dir, e.Name))
		if err != nil {
			return fmt.Errorf("integrity: %s: %w", e.Name, err)
		}
		if got != e.SHA256Hex {
			return fmt.Errorf("integrity: %s: checksum mismatch (have %s, sums file says %s)", e.Name, got, e.SHA256Hex)
		}
	}
	return nil
}

// Seal implements the release sealing step (plan §4.7 tier (b)): the
// staging directory must contain exactly wantFiles (plus the sums file
// itself, regenerated here); any stray file fails the seal. Returns the
// verification result of the freshly written sums file.
func Seal(stagingDir string, wantFiles []string, sumsName string) error {
	entries, err := os.ReadDir(stagingDir)
	if err != nil {
		return err
	}
	want := make(map[string]bool, len(wantFiles))
	for _, f := range wantFiles {
		want[f] = true
	}
	for _, ent := range entries {
		name := ent.Name()
		if name == sumsName {
			continue // regenerated below
		}
		if ent.IsDir() {
			return fmt.Errorf("integrity: stray directory %q in staging dir fails the seal", name)
		}
		if !want[name] {
			return fmt.Errorf("integrity: stray file %q in staging dir fails the seal", name)
		}
		delete(want, name)
	}
	if len(want) > 0 {
		missing := make([]string, 0, len(want))
		for f := range want {
			missing = append(missing, f)
		}
		sort.Strings(missing)
		return fmt.Errorf("integrity: staging dir missing release files: %s", strings.Join(missing, ", "))
	}
	sumsPath := filepath.Join(stagingDir, sumsName)
	if err := WriteSums(sumsPath, wantFiles); err != nil {
		return err
	}
	return Verify(sumsPath)
}
