name: CI

on:
  push:
    branches:
      - main
      - dev
  pull_request:

env:
  GOPATH: ${{ github.workspace }}/go

jobs:
  build:
    name: Build
    runs-on: ubuntu-24.04
    steps:
      - &checkout-harmony
        name: Checkout harmony
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 #v6.0.0
        with:
          ref: ${{ github.sha }}
          path: go/src/github.com/harmony-one/harmony
          persist-credentials: false

      - &checkout-mcl
        name: Checkout mcl
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 #v6.0.0
        with:
          repository: harmony-one/mcl
          ref: master
          path: go/src/github.com/harmony-one/mcl
          persist-credentials: false

      - &checkout-bls
        name: Checkout bls
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 #v6.0.0
        with:
          repository: harmony-one/bls
          ref: master
          path: go/src/github.com/harmony-one/bls
          persist-credentials: false

      - &setup-go
        name: Set up Go
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c #v6.4.0
        with:
          go-version: '1.24.2'
          cache-dependency-path: go/src/github.com/harmony-one/harmony/go.sum

      - &build-mcl
        name: Build mcl
        run: make -j4
        working-directory: go/src/github.com/harmony-one/mcl

      - &build-bls
        name: Build bls
        run: make BLS_SWAP_G=1 -j4
        working-directory: go/src/github.com/harmony-one/bls

      - &build-harmony
        name: Build harmony
        run: make
        working-directory: go/src/github.com/harmony-one/harmony

  go-checker:
    name: Go Checker
    runs-on: ubuntu-24.04
    steps:
      - *checkout-harmony
      - *checkout-mcl
      - *checkout-bls
      - *setup-go
      - *build-mcl
      - *build-bls
      - *build-harmony

      - name: Install tools
        run: |
          go install golang.org/x/tools/cmd/goimports@v0.30.0
          go install github.com/fjl/gencodec@v0.1.1
        working-directory: go/src/github.com/harmony-one/harmony

      - name: Run go checker
        run: |
          make go-get
          bash ./scripts/travis_go_checker.sh
        working-directory: go/src/github.com/harmony-one/harmony

  rpc-checker:
    name: RPC Checker
    runs-on: ubuntu-24.04
    steps:
      - *checkout-harmony
      - *checkout-mcl
      - *checkout-bls
      - *setup-go
      - *build-mcl
      - *build-bls
      - *build-harmony
      - name: Checkout harmony-test
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 #v6.0.0
        with:
          repository: harmony-one/harmony-test
          path: go/src/github.com/harmony-one/harmony-test
          persist-credentials: false

      - name: Run RPC checker
        run: |
          make go-get
          bash ./scripts/travis_rpc_checker.sh
        working-directory: go/src/github.com/harmony-one/harmony
        env: &travis-pr-env
          TRAVIS_PULL_REQUEST_SLUG: ${{ github.event.pull_request.head.repo.full_name }}
          TRAVIS_PULL_REQUEST_BRANCH: ${{ github.head_ref }}
          TRAVIS_BRANCH: ${{ github.ref_name }}

  pyhmy-checker:
    name: pyhmy Checker
    runs-on: ubuntu-24.04
    steps:
      - *checkout-harmony
      - *checkout-mcl
      - *checkout-bls
      - *setup-go
      - *build-mcl
      - *build-bls
      - *build-harmony
      - name: Run pyhmy checker
        run: |
          make go-get
          bash ./scripts/travis_pyhmy_checker.sh
        working-directory: go/src/github.com/harmony-one/harmony
        env: *travis-pr-env
