name: GitHub Actions Security Analysis with zizmor 🌈 and actionlint 

on:
  push:
    branches:
      - main
      - dev
    paths:
      - '.github/workflows/**/*.yml'
      - '.github/workflows/**/*.yaml'

  pull_request:
    branches: ["**"]
    paths:
      - '.github/workflows/**/*.yml'
      - '.github/workflows/**/*.yaml'

permissions: {}

jobs:
  zizmor:
    name: Run zizmor 🌈
    runs-on: ubuntu-latest
    steps:
      - &checkout-repository
        name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 #v7.0.1
        with:
          persist-credentials: false
          fetch-depth: 1

      - name: Run zizmor 🌈
        uses: zizmorcore/zizmor-action@70fb788f84895a7701f5643d103d587e460b5c99 # v0.6.3
        with:
          inputs: ./.github/
          advanced-security: false

  actionlint:
    name: Run actionlint
    runs-on: ubuntu-latest
    steps:
      - *checkout-repository
      - name: Run actionlint # Docu: https://github.com/rhysd/actionlint/blob/main/docs/usage.md#docker
        uses: docker://rhysd/actionlint@sha256:9d36088643581e728c969f35141f88139fec77280b2be23c1f66f8e40e1025e7 #v1.7.12
