name: GitHub Actions Security Analysis with zizmor 🌈

on:
  push:
    branches:
      - main
      - dev
    paths:
      - '.github/workflows/**/*.yml'
      - '.github/workflows/**/*.yaml'

  pull_request:
    branches: ["**"]
    paths:
      - '.github/workflows/**/*.yml'
      - '.github/workflows/**/*.yaml'

permissions: {}

jobs:
  zizmor:
    name: Run zizmor 🌈
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 #v7.0.0
        with:
          persist-credentials: false
          fetch-depth: 1

      - name: Run zizmor 🌈
        uses: zizmorcore/zizmor-action@192e21d79ab29983730a13d1382995c2307fbcaa # v0.5.7
        with:
          inputs: ./.github/
          advanced-security: false
